# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzViOTk5NWM1YzMzMDA4MzI3OTg3NTBlYzVjZTMwY2M2MDNmNzdkODM5ZjQ2YWNmY2ViZmFhOWRjZWIyZjkyZGUwOTc3YzQ3YzA4ZTQ3MDMwMGQ2NzAzYmM4NmRkMTk3ZmYxYzY5NWFmYjkyOWU3M2FlYWVlOTJjZWE3M2E2NmI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
